apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    app: auth-api
    service: auth-api
spec:
  ports:
    - port: 3020
      name: grpc
  selector:
    app: auth-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-demo-auth-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      serviceAccountName: microservices-demo-auth-api
      containers:
        - name: auth-api
          image: frperezr/microservices-demo-auth-api:0.0.1
          ports:
            - containerPort: 3020
          env:
            - name: PORT
              value: "3020"
            - name: USERS_HOST
              value: users-api
            - name: USERS_PORT
              value: "3050"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
