apiVersion: v1
kind: ConfigMap
metadata:
  name: budgets-postgres-config
  labels:
    app: budgets-postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: budgets-postgres-pv-volume
  labels:
    type: local
    app: budgets-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/budgets"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: budgets-postgres-pv-claim
  labels:
    app: budgets-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgets-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgets-postgres
  template:
    metadata:
      labels:
        app: budgets-postgres
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: budgets-postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: budgets-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: budgets-postgresdb
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: budgets-postgresdb
          persistentVolumeClaim:
            claimName: budgets-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: budgets-postgres
  labels:
    app: budgets-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: budgets-postgres
