apiVersion: v1
kind: Service
metadata:
  name: countries-api
  labels:
    app: countries-api
    service: countries-api
spec:
  ports:
    - port: 3030
      name: http
  selector:
    app: countries-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-demo-countries-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries-api
  labels:
    app: countries-api
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countries-api
  template:
    metadata:
      labels:
        app: countries-api
    spec:
      serviceAccountName: microservices-demo-countries-api
      containers:
        - name: countries-api
          image: frperezr/microservices-demo-countries-api:0.0.1
          ports:
            - containerPort: 3030
          env:
            - name: PORT
              value: "3030"
            - name: POSTGRES_DSN
              value: postgres://postgres:postgres@countries-postgres:5432/postgres?sslmode=disable
            - name: PROTO_PATH
              value: /countries-api/pb/demo.proto
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
