apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
    app: users-api
    service: users-api
spec:
  ports:
    - port: 3050
      name: grpc
  selector:
    app: users-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-demo-users-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      serviceAccountName: microservices-demo-users-api
      containers:
        - name: users-api
          image: frperezr/microservices-demo-users-api:0.0.1
          ports:
            - containerPort: 3050
          env:
            - name: POSTGRES_DSN
              value: postgres://postgres:postgres@users-postgres:5432/postgres?sslmode=disable
            - name: PORT
              value: "3050"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: users-postgresdb
          persistentVolumeClaim:
            claimName: users-postgres-pv-claim
